package ipn.escom.meteora.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF4285F4)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDBE1FF)
val onPrimaryContainerLight = Color(0xFF00174B)
val secondaryLight = Color(0xFF595E72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDDE1F9)
val onSecondaryContainerLight = Color(0xFF161B2C)
val tertiaryLight = Color(0xFFCDEDA3)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDCE7C8)
val onTertiaryContainerLight = Color(0xFF102000)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAF8FF)
val onBackgroundLight = Color(0xFF1A1B21)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF1A1B21)
val surfaceVariantLight = Color(0xFFE2E2EC)
val onSurfaceVariantLight = Color(0xFF45464F)
val outlineLight = Color(0xFF757680)
val outlineVariantLight = Color(0xFFC5C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFB4C5FF)
val surfaceDimLight = Color(0xFFDAD9E0)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3FA)
val surfaceContainerLight = Color(0xFFEEEDF4)
val surfaceContainerHighLight = Color(0xFFE8E7EF)
val surfaceContainerHighestLight = Color(0xFFE3E2E9)

val primaryDark = Color(0xFFB4C5FF)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFF334478)
val onPrimaryContainerDark = Color(0xFFDBE1FF)
val secondaryDark = Color(0xFFC1C5DD)
val onSecondaryDark = Color(0xFF2B3042)
val secondaryContainerDark = Color(0xFF414659)
val onSecondaryContainerDark = Color(0xFFDDE1F9)
val tertiaryDark = Color(0xFFB1D18A)
val onTertiaryDark = Color(0xFF1F3701)
val tertiaryContainerDark = Color(0xFF354E16)
val onTertiaryContainerDark = Color(0xFFCDEDA3)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121318)
val onBackgroundDark = Color(0xFFE3E2E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE3E2E9)
val surfaceVariantDark = Color(0xFF45464F)
val onSurfaceVariantDark = Color(0xFFC5C6D0)
val outlineDark = Color(0xFF8F909A)
val outlineVariantDark = Color(0xFF45464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E9)
val inverseOnSurfaceDark = Color(0xFF2F3036)
val inversePrimaryDark = Color(0xFF4B5C92)
val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF38393F)
val surfaceContainerLowestDark = Color(0xFF0D0E13)
val surfaceContainerLowDark = Color(0xFF1A1B21)
val surfaceContainerDark = Color(0xFF1E1F25)
val surfaceContainerHighDark = Color(0xFF292A2F)
val surfaceContainerHighestDark = Color(0xFF34343A)

val amber = Color(0xFFFFD600)
val amberLight = Color(0xFFF8EB9E)
val green = Color(0xFF34AB53)

val orange = Color(0xFFFC4100)
val blue = Color(0xFF3E6D9C)
val indigo = Color(0xFF615EFC)

val lightBackground = Color(0xFFCDE5FF)
val lightOnBackground = Color(0xFFFCFCFE)